# Generated by Django 5.2 on 2025-09-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese titulo del curso', max_length=100)),
                ('categoria', models.CharField(help_text='Ingrese la categoria del curso', max_length=100)),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripcion para el curso')),
                ('duracion', models.CharField(help_text='Ingrese duracion del curso. Ej: 20 horas, 2 semanas...', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Ingrese precio del curso. Ej: 39, 39.99', max_digits=6)),
                ('fecha_inicio', models.CharField(help_text='Ingrese fecha de inicio. Ej: 10 de enero', max_length=50)),
                ('cupo', models.CharField(help_text='Ingrese cantidad de cupos. Ej: Max. 30 personas', max_length=100)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
