# Generated by Django 5.2 on 2025-09-18 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_rename_contactos_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Categoría del curso.', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contacto',
            name='origen',
            field=models.CharField(choices=[('index', 'Index'), ('cursos', 'Cursos')], default='index', max_length=20),
        ),
        migrations.AddField(
            model_name='contacto',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.categoria'),
        ),
    ]
