# Generated by Django 5.2 on 2025-09-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_remove_contacto_taller_contacto_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cc_ami',
            field=models.BooleanField(default=False, help_text='Correo adicional (CC) opcional'),
        ),
    ]
