# Generated by Django 6.0 on 2025-12-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_contacto_cc_ami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
