# Generated by Django 5.2 on 2025-09-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgCursos'),
        ),
    ]
