# Generated by Django 5.2 on 2025-09-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_rename_cursos_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='Contacto',
        ),
    ]
