# Generated by Django 5.2 on 2025-09-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_categoria_contacto_fecha_envio_contacto_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='taller',
            field=models.ForeignKey(blank=True, help_text='Seleccione el taller de interés', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.curso'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
