# Generated by Django 5.2 on 2025-09-18 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_contacto_taller_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='taller',
        ),
        migrations.AddField(
            model_name='contacto',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Seleccione el curso de interés', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.curso'),
        ),
    ]
